# -*- coding: utf-8 -*-
"""23101090_Disk Scheduling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W69Rmx86wOZ8NxmX9Y93CBXHr_BA6l8j
"""

def sstf(requests, head):
    sequence = []
    total_seek = 0
    queue = requests.copy()
    current = head

    while queue:
        closest = min(queue, key=lambda x: abs(x - current))
        total_seek += abs(closest - current)
        sequence.append(closest)
        current = closest
        queue.remove(closest)

    return sequence, total_seek

requests = [0, 13, 41, 50, 63, 89, 100]
head = 46

seq, total = sstf(requests, head)

print("Seek Sequence:", seq)
print("Total Seek Operations:", total)

requestSequence = [176, 51, 50, 40, 39, 100]
head = 35

seekOperation = 0
old = head
print(f"request sequence : {requestSequence}")

for new in requestSequence:
    steps = abs(new - old)
    print(f"{old:<4} to {new:<4}: {steps}")
    seekOperation += steps
    old = new

print(f"total seek operation : {seekOperation}")

def scan(requests, head, direction="left", disk_size=101):
    left = sorted([r for r in requests if r < head], reverse=True)
    right = sorted([r for r in requests if r > head])

    if direction == "left":
        if 0 not in left:
            left.append(0)
        seq = left + right
    else:
        max_track = disk_size - 1
        if max_track not in right:
            right.append(max_track)
        seq = right + left

    total_seek = 0
    curr = head
    for track in seq:
        total_seek += abs(track - curr)
        curr = track

    return seq, total_seek


requests = [0, 13, 41, 50, 63, 89, 100]
head = 46


print("Left Direction :", scan(requests, head, "left"))
print("Right Direction:", scan(requests, head, "right"))