# -*- coding: utf-8 -*-
"""23101090,FCFS Disk Scheduling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cd533Ufd8tCgxVPhe_rBQo4aeiqZJVoz
"""

requestSequence = [176, 51, 50, 40, 39, 100]
head = 35

seekOperation = 0
old = head
print(f"request sequence : {requestSequence}")

for new in requestSequence:
    steps = abs(new - old)
    print(f"{old:<4} to {new:<4}: {steps}")
    seekOperation += steps
    old = new

print(f"total seek operation : {seekOperation}")

