# -*- coding: utf-8 -*-
"""Priority CPU Scheduling Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMHvjLvasdQio9GLrriWKf6BClWtCXu0
"""

# Preemptive Priority CPU Scheduling Algorithm
n = int(input("Enter total number of processes: "))

processes = []
for i in range(n):
    print(f"\n--- Process P{i+1} ---")
    at = int(input("Arrival Time: "))
    bt = int(input("Burst Time: "))
    prio = int(input("Priority: "))
    processes.append({'pid': f"P{i+1}", 'at': at, 'bt': bt, 'prio': prio, 'rem_bt': bt})

current_time = 0
completed = 0
ct, tat, wt = [0] * n, [0] * n, [0] * n

while completed < n:
    idx = -1
    min_prio = float('inf')

    for i in range(n):
        if processes[i]['at'] <= current_time and processes[i]['rem_bt'] > 0:
            if processes[i]['prio'] < min_prio:
                min_prio = processes[i]['prio']
                idx = i
            elif processes[i]['prio'] == min_prio:
                if processes[i]['at'] < processes[idx]['at']:
                    idx = i

    if idx == -1:
        current_time += 1
    else:
        processes[idx]['rem_bt'] -= 1
        current_time += 1

        if processes[idx]['rem_bt'] == 0:
            completed += 1
            ct[idx] = current_time
            tat[idx] = ct[idx] - processes[idx]['at']
            wt[idx] = tat[idx] - processes[idx]['bt']

print("\nProcess\tArrival\tBurst\tPriority\tCompletion\tTAT\tWT")
for i in range(n):
    print(f"{processes[i]['pid']}\t{processes[i]['at']}\t{processes[i]['bt']}\t{processes[i]['prio']}\t\t{ct[i]}\t\t{tat[i]}\t{wt[i]}")

print(f"\nAverage Turnaround Time (TAT): {sum(tat)/n:.2f}")
print(f"Average Waiting Time (WT): {sum(wt)/n:.2f}")

# Non-Preemptive Priority CPU Scheduling Algorithm
n = int(input("Enter total number of processes: "))

processes = []
for i in range(n):
    print(f"\n--- Process P{i+1} ---")
    at = int(input("Arrival Time: "))
    bt = int(input("Burst Time: "))
    prio = int(input("Priority: "))
    processes.append({'pid': f"P{i+1}", 'at': at, 'bt': bt, 'prio': prio, 'done': False})

current_time = 0
completed = 0
ct, tat, wt = [0] * n, [0] * n, [0] * n

while completed < n:
    idx = -1
    min_prio = float('inf')

    for i in range(n):
        if processes[i]['at'] <= current_time and not processes[i]['done']:
            if processes[i]['prio'] < min_prio:
                min_prio = processes[i]['prio']
                idx = i
            elif processes[i]['prio'] == min_prio:
                if processes[i]['at'] < processes[idx]['at']:
                    idx = i

    if idx == -1:
        current_time += 1
    else:
        current_time += processes[idx]['bt']
        ct[idx] = current_time
        tat[idx] = ct[idx] - processes[idx]['at']
        wt[idx] = tat[idx] - processes[idx]['bt']
        processes[idx]['done'] = True
        completed += 1

print("\nProcess\tArrival\tBurst\tPriority\tCompletion\tTAT\tWT")
for i in range(n):
    print(f"{processes[i]['pid']}\t{processes[i]['at']}\t{processes[i]['bt']}\t{processes[i]['prio']}\t\t{ct[i]}\t\t{tat[i]}\t{wt[i]}")

print(f"\nAverage Turnaround Time (TAT): {sum(tat)/n:.2f}")
print(f"Average Waiting Time (WT): {sum(wt)/n:.2f}")