# -*- coding: utf-8 -*-
"""Round Robin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XNDJgI6TPZ5DLAYFp5HHyEVx-pOPF7cO
"""

n = int(input("Enter number of processes: "))

burst = []
arrival = []

for i in range(n):
    bt = int(input(f"Enter burst time for P{i+1}: "))
    burst.append(bt)
    arrival.append(0)

print("Burst Time:", burst)
print("Arrival Time:", arrival)

quantum = int(input("Enter time quantum: "))

remaining = burst.copy()
completion = [0] * n
turnaround = [0] * n
waiting = [0] * n

current_time = 0
queue = list(range(n))

while queue:
    process = queue.pop(0)

    if remaining[process] > quantum:
        current_time += quantum
        remaining[process] -= quantum
        queue.append(process)

    else:
        current_time += remaining[process]
        remaining[process] = 0

        completion[process] = current_time
        turnaround[process] = completion[process] - arrival[process]
        waiting[process] = turnaround[process] - burst[process]

print("\nPID\tBT\tCT\tTAT\tWT")

total_wait = 0
total_turn = 0

for i in range(n):
    print(f"P{i+1}\t{burst[i]}\t{completion[i]}\t"
          f"{turnaround[i]}\t{waiting[i]}")

    total_wait += waiting[i]
    total_turn += turnaround[i]

print(f"\nAverage Waiting Time = {total_wait / n:.2f}")
print(f"Average Turnaround Time = {total_turn / n:.2f}")