# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-C2jtUdUPPTlRezQZDUzErFmzLfm-xQT
"""

n = int(input("Enter number of processes: "))

processes = []

# Input
for i in range(n):
    print(f"\nProcess P{i+1}")

    at = int(input("Arrival Time: "))
    bt = int(input("Burst Time: "))

    processes.append({
        "pid": f"P{i+1}",
        "at": at,
        "bt": bt
    })




sjf = []

for p in processes:
    sjf.append({
        "pid": p["pid"],
        "at": p["at"],
        "bt": p["bt"],
        "ct": 0,
        "tat": 0,
        "wt": 0
    })

time = 0
completed = 0

while completed < n:

    available = []

    for p in sjf:
        if p["at"] <= time and p["ct"] == 0:
            available.append(p)


    if not available:
        time += 1
        continue


    current = min(
        available,
        key=lambda p: (p["bt"], p["at"])
    )

    time += current["bt"]

    current["ct"] = time
    current["tat"] = current["ct"] - current["at"]
    current["wt"] = current["tat"] - current["bt"]

    completed += 1


print("\n========== NON-PREEMPTIVE SJF ==========")
print("PID\tAT\tBT\tCT\tTAT\tWT")

total_tat = 0
total_wt = 0

for p in sjf:
    print(
        f'{p["pid"]}\t{p["at"]}\t{p["bt"]}\t'
        f'{p["ct"]}\t{p["tat"]}\t{p["wt"]}'
    )

    total_tat += p["tat"]
    total_wt += p["wt"]

print(f"\nAverage TAT = {total_tat / n:.2f}")
print(f"Average WT  = {total_wt / n:.2f}")



srtf = []

for p in processes:
    srtf.append({
        "pid": p["pid"],
        "at": p["at"],
        "bt": p["bt"],
        "remaining": p["bt"],
        "ct": 0,
        "tat": 0,
        "wt": 0
    })

time = 0
completed = 0

while completed < n:

    available = []

    for p in srtf:
        if p["at"] <= time and p["remaining"] > 0:
            available.append(p)


    if not available:
        time += 1
        continue


    current = min(
        available,
        key=lambda p: (p["remaining"], p["at"])
    )


    current["remaining"] -= 1
    time += 1


    if current["remaining"] == 0:

        current["ct"] = time
        current["tat"] = current["ct"] - current["at"]
        current["wt"] = current["tat"] - current["bt"]

        completed += 1


print("\n========== PREEMPTIVE SJF (SRTF) ==========")
print("PID\tAT\tBT\tCT\tTAT\tWT")

total_tat = 0
total_wt = 0

for p in srtf:
    print(
        f'{p["pid"]}\t{p["at"]}\t{p["bt"]}\t'
        f'{p["ct"]}\t{p["tat"]}\t{p["wt"]}'
    )

    total_tat += p["tat"]
    total_wt += p["wt"]

print(f"\nAverage TAT = {total_tat / n:.2f}")
print(f"Average WT  = {total_wt / n:.2f}")